language: python
os: linux

jobs:
  include:
    - name: "Python 3.7.x on Bionic Linux"
      os: linux
      dist: bionic
      python: "3.7"
    - name: "Python 3.8.x on Bionic Linux"
      os: linux
      dist: bionic
      python: "3.8"
    - name: "Python 'nightly' on Bionic Linux"
      os: linux
      dist: bionic
      python: "nightly"

    - name: "Python 3.7.x on Focal Linux"
      os: linux
      dist: focal
      python: "3.7"
    - name: "Python 3.8.x on Focal Linux"
      os: linux
      dist: focal
      python: "3.8"
    - name: "Python 'nightly' on Focal Linux"
      os: linux
      dist: focal
      python: "nightly"

    - name: "Python 3.8.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.6
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

    - name: "Python 3.9.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -r .requirements.txt

script:
  - coverage run -m pytest

after_success:
  - coveralls
